<?php

namespace AppBundle\Repository;

use AppBundle\Entity\AccountType;
use AppBundle\Entity\Transaction;
use Doctrine\Bundle\DoctrineBundle\Repository\ServiceEntityRepository;
use Doctrine\ORM\EntityManagerInterface;
use Doctrine\ORM\Mapping\ClassMetadata;
use Symfony\Bridge\Doctrine\RegistryInterface;


/**
 * TransactionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TransactionRepository extends ServiceEntityRepository
{
    public function __construct(RegistryInterface $registry)
    {
        parent::__construct($registry, Transaction::class);
//        parent::__construct($registry, AccountType::class);
    }

    /**
     * @param $value
     * @return array
     */
    public function discoverSaldo($value)
    {
        return $this->createQueryBuilder('t')
            ->where('t.userId = :value')->setParameter('value', $value)
            ->groupBy('t.accountTypeId')
            ->select('SUM(t.transactionValue) as saldo')
            ->getQuery()
            ->getResult();
    }

    /**
     * @return array
     */
    public function getHistory($value){
        return $this->createQueryBuilder('t')
            ->where('t.userId = :value')->setParameter('value', $value)
//            ->groupBy('t.accountTypeId')
            ->select('t.name as name')
            ->getQuery()
            ->getResult();
    }

}
