<?php

namespace AppBundle\Repository;
use AppBundle\Entity\TransactionStatus;
use Doctrine\ORM\EntityManagerInterface;
use Doctrine\ORM\Mapping\ClassMetadata;

/**
 * TransactionStatusRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TransactionStatusRepository extends \Doctrine\ORM\EntityRepository
{
    public function __construct(EntityManagerInterface $entityManager)
    {
        parent::__construct($entityManager, new ClassMetadata(TransactionStatus::class));
    }
}
