<?php

namespace AppBundle\Repository;

/**
 * TransactionStatusRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TransactionStatusRepository extends \Doctrine\ORM\EntityRepository
{
}
